language: php
php:
    - '5.6'
services:
    - mysql
dist: trusty
addons:
    hosts:
        - student.dev
    chrome: stable
before_install:
    - php /home/travis/.phpenv/versions/5.6/bin/composer self-update
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
install:
    - composer install
before_script:
    - mysql -e 'create database bict_encoder;'
    # starting demo server
    - sudo apt-get update
    - sudo apt-get install apache2 libapache2-mod-fastcgi
    # enable php-fpm
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    # configure apache virtual hosts
    - sudo cp -f resources/travis-ci-apache /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    - sudo service apache2 restart
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    - rackup  # start a Web server
    - sleep 3 # give Web server some time to bind to sockets, etc
script:
    - php artisan migrate
    - php artisan key:generate
    - php artisan config:clear
    - vendor/phpunit/phpunit/phpunit
    - php artisan config:cache
    - vendor/bin/behat
